---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    operator: {{ .Values.app.name }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "create", "update", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["savilabs.io"]
    resources: ["globalobjects"]
    verbs: ["get", "list", "watch", "put", "post", "patch"]
  - apiGroups: ["events.k8s.io", ""]
    resources: ["events"]
    verbs: ["create"]
