---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalobjects.savilabs.io
  labels:
    operator: {{ .Values.app.name }}
spec:
  scope: Namespaced
  group: savilabs.io
  version: v1alpha1
  names:
    kind: GlobalObject
    singular: globalobject
    plural: globalobjects
    shortNames:
    - go
  additionalPrinterColumns:
    - name: Object Type
      type: string
      priority: 0
      JSONPath: .spec.type
      description: Type of the object to replicate into namespace(s)
    - name: Object Name
      type: string
      priority: 0
      JSONPath: .spec.name
      description: Name of the object to replicate into namespace(s)
    - name: Object Target Name
      type: string
      priority: 0
      JSONPath: .spec.targetName
      description: Name of the object in the target namespace(s)
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            type:
              type: string
              description: "Type of the object to replicate into namespace(s)"
              enum: ["secret", "configmap"]
            name:
              type: string
              description: "Name of the object to replicate into namespace(s)"
            targetName:
              type: string
              description: "Name of the object in the target namespace(s)"
            targetNamespaces:
              type: array
              description: "Namespace(s) to which the object has to be replicated"
          required: ["type", "name", "targetNamespaces"]
