---
apiVersion: v1
kind: Namespace
metadata:
  name: admin
savithru_ml7@cloudshell:~/final/agumbe/manifests (my-k8s-265623)$ cat 02-rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-operator
  namespace: admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-operator
subjects:
  - kind: ServiceAccount
    name: secrets-operator
    namespace: admin
