---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agumbe
  namespace: admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agumbe
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps", "namespaces"]
  verbs: ["get", "create", "update", "list"]
- apiGroups: ["savilabs.io"]
  resources: ["globalobjects"]
  verbs: ["get", "list", "watch", "put", "post", "patch"]
- apiGroups: ["events.k8s.io", ""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agumbe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agumbe
subjects:
  - kind: ServiceAccount
    name: agumbe
    namespace: admin
