---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-operator
  namespace: admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "list"]
- apiGroups: ["savilabs.io"]
  resources: ["globalsecrets"]
  verbs: ["get", "list", "watch", "put", "post", "patch"]
- apiGroups: ["events.k8s.io", ""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-operator
subjects:
  - kind: ServiceAccount
    name: secrets-operator
    namespace: admin
