---
apiVersion: savilabs.io/v1alpha1
kind: GlobalSecret
metadata:
  name: test-global-secret
  namespace: admin
spec:
  secretName: test-secret-mar-18-2020
  targetSecretName: my-secret
  targetNamespaces:
    - blue
    - green
