---
apiVersion: savilabs.io/v1alpha1
kind: GlobalObject
metadata:
  name: global-configmap
  namespace: agumbe
spec:
  type: ConfigMap
  name: cm-april-2020
  targetName: my-configmap
  targetNamespaces:
    - red
    - blue
    - green
